### ISSUE TITLE
No Licence?

### ISSUE THREAD

**Issue by drsassafras** [WikiSuite/app-php-engines#8]
Not sure exactly how the licencing works, but if this is a separate project, I don't see any licencing info here. Perhaps it should be mentioned that this is open source, and falls under the ???? licence, with a link to the licence details.

A readme would also be nice.

**Comment by pcbaldwin** [comment]
There's a ClearOS development tool to generate a basic README:

    clearos readme

It takes the information in the deploy/info.php and converts it to a simple Markdown README.  Done.

As for the licenses, I'll add that to the tool.  Most of the apps are GPLv3 (GUI/Controllers) and LGPLv3 (Libraries).  At the very least, the clearos development tool can drop those into the project.

**Comment by pcbaldwin** [comment]
Licenses were added in the packaging subdirectory.  On RPM installs, the API license will end up in /usr/share/doc/app-php-engines-core and the non-API license will end up in /usr/share/doc/app-php-engines.

**Comment by drsassafras** [comment]
Looks good to me!
